spring:
  application:
    name: finup

  config: # 사용 설정 파일
    import:
      - classpath:settings/application-db.yml
      - classpath:settings/application-web.yml
      - classpath:settings/application-mail.yml
      - classpath:settings/application-security.yml
      - classpath:settings/application-ai.yml
      - classpath:settings/application-cache.yml

  profiles: # 활성 프로필 (local, prod)
    active: ${ACTIVE_PROFILE}


### 서버 포트 ###

server:
  port: ${SERVER_PORT} # 서버 포트

### 특정 기술에 속하지 않는 커스텀 상수 ###

app:
  domain: ${APP_DOMAIN} # 백엔드 도메인
  origin: ${APP_ORIGIN}

  file:
    dir: ${FILE_DIR} # 파일 경로
    domain: ${FILE_DOMAIN} # 파일 접근 도메인
    handler: ${FILE_HANDLER:} # 로컬 핸들러 경로 (기본값 설정)

    s3:
      bucket-name: ${S3_BUCKET_NAME:}

### 외부 API 호출을 위한 상수 ###

api:
  kis:
    client:
      id: ${API_KIS_CLIENT_ID}
      secret: ${API_KIS_CLIENT_SECRET}

  naver-news:
    client:
      id: ${API_NAVER_NEWS_CLIENT_ID}
      secret: ${API_NAVER_NEWS_CLIENT_SECRET}

  youtube:
    key: ${API_YOUTUBE_KEY}

  kexim:
    key: ${API_KEXIM_KEY}

  open-portal:
    key: ${API_OPENPORTAL_KEY}